### ISSUE TITLE
Some FM channels going out of sync

### ISSUE THREAD

**Issue by sreuter** [GbaCretin/dmf2mlm#5]
It seems like some of the FM tracks sometimes go out of sync with the rest of the song. Could the way we skip unsupported effects at the moment be the cause of this?

(also, please feel free to move to https://github.com/GbaCretin/Mezz-Estate-NeoGeo-Audio-Driver should this be a driver issue instead)

**Comment by ghost** [comment]
The issue was caused during the conversion from the dmf tracker module to the mlm events. When a non empty row didn't result in any new events added, the next non empty row messed up the timing.
